import XCTest
@testable import SwiftPipeExtractor

/// Smoke tests for the stream model connected component: builders that copy
/// fields from an ItagItem, equalStats, Frameset math, and the collector +
/// extractor wiring (which de-risks the YouTube StreamExtractor port).
final class StreamModelTests: XCTestCase {

    func testItagItemLookup() throws {
        XCTAssertTrue(ItagItem.isSupported(140))
        XCTAssertFalse(ItagItem.isSupported(99999))
        let itag = try ItagItem.getItag(140)
        XCTAssertEqual(itag.id, 140)
        XCTAssertEqual(itag.itagType, .AUDIO)
        XCTAssertEqual(itag.getMediaFormat(), .M4A)
        XCTAssertEqual(itag.getAverageBitrate(), 128)
        XCTAssertThrowsError(try ItagItem.getItag(99999))
    }

    func testAudioStreamBuilderCopiesItagFields() {
        let itag = ItagItem(140, .AUDIO, .M4A, 128)
        itag.setBitrate(131072)
        itag.setCodec("mp4a.40.2")
        let stream = AudioStream.Builder()
            .setId("140")
            .setContent("https://example.com/audio", true)
            .setMediaFormat(.M4A)
            .setAverageBitrate(128)
            .setItagItem(itag)
            .build()
        XCTAssertEqual(stream.getId(), "140")
        XCTAssertEqual(stream.getContent(), "https://example.com/audio")
        XCTAssertTrue(stream.isUrl())
        XCTAssertEqual(stream.getItag(), 140)
        XCTAssertEqual(stream.getBitrate(), 131072)
        XCTAssertEqual(stream.getCodec(), "mp4a.40.2")
        XCTAssertEqual(stream.getFormat(), .M4A)
        XCTAssertNotNil(stream.getItagItem())
    }

    func testVideoStreamBuilderAndEqualStats() {
        func make(_ res: String, videoOnly: Bool) -> VideoStream {
            VideoStream.Builder()
                .setId("137")
                .setContent("https://example.com/video", true)
                .setMediaFormat(.MPEG_4)
                .setResolution(res)
                .setIsVideoOnly(videoOnly)
                .build()
        }
        let a = make("1080p", videoOnly: true)
        let b = make("1080p", videoOnly: true)
        let c = make("720p", videoOnly: true)
        XCTAssertTrue(a.equalStats(b))
        XCTAssertFalse(a.equalStats(c))
        XCTAssertTrue(Stream.containSimilarStream(a, [c, b]))
        XCTAssertFalse(Stream.containSimilarStream(a, [c]))
        XCTAssertTrue(a.isVideoOnly())
        XCTAssertEqual(a.getResolution(), "1080p")
    }

    func testSubtitlesStreamBuilder() throws {
        let stream = try SubtitlesStream.Builder()
            .setContent("https://example.com/sub.vtt", true)
            .setMediaFormat(.VTT)
            .setLanguageCode("en")
            .setAutoGenerated(false)
            .build()
        XCTAssertEqual(stream.getLanguageTag(), "en")
        XCTAssertEqual(stream.getExtension(), "vtt")
        XCTAssertFalse(stream.isAutoGenerated())
        XCTAssertNil(stream.getItagItem())
    }

    func testFramesetBounds() {
        let frameset = Frameset(
            ["https://example.com/sb0.jpg"],
            160, 90, // frame w/h
            100,     // total count
            5000,    // duration per frame (ms)
            5, 5)    // frames per page x/y
        // First frame at position 0
        XCTAssertEqual(frameset.getFrameBoundsAt(0), [0, 0, 0, 160, 90])
        // Position beyond the end falls back to the first frame
        let beyond = frameset.getFrameBoundsAt(10_000_000)
        XCTAssertEqual(beyond, [0, 0, 0, 160, 90])
    }

    func testStreamInfoItemsCollectorWithMockExtractor() {
        let collector = StreamInfoItemsCollector(0)

        let good = MockStreamInfoItemExtractor(
            name: "Test Video",
            url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            streamType: .VIDEO_STREAM,
            duration: 212,
            viewCount: 1_400_000_000)
        collector.commit(good)

        // An ad is silently skipped (FoundAdException)
        let ad = MockStreamInfoItemExtractor(
            name: "Ad", url: "https://ad", streamType: .VIDEO_STREAM,
            duration: 0, viewCount: 0, isAd: true)
        collector.commit(ad)

        let items = collector.getItems()
        XCTAssertEqual(items.count, 1)
        XCTAssertEqual(items[0].getName(), "Test Video")
        XCTAssertEqual(items[0].getStreamType(), .VIDEO_STREAM)
        XCTAssertEqual(items[0].getDuration(), 212)
        XCTAssertEqual(items[0].getViewCount(), 1_400_000_000)
        XCTAssertTrue(collector.getErrors().isEmpty)
    }

    func testMultiInfoItemsCollectorDispatchesByType() throws {
        let collector = MultiInfoItemsCollector(0)
        collector.commit(MockStreamInfoItemExtractor(
            name: "V", url: "https://v", streamType: .VIDEO_STREAM,
            duration: 1, viewCount: 1))
        collector.commit(MockChannelInfoItemExtractor(name: "C", url: "https://c"))
        let items = collector.getItems()
        XCTAssertEqual(items.count, 2)
        XCTAssertTrue(items[0] is StreamInfoItem)
        XCTAssertTrue(items[1] is ChannelInfoItem)
    }
}

private struct MockStreamInfoItemExtractor: StreamInfoItemExtractor {
    let name: String
    let url: String
    let streamType: StreamType
    let duration: Int64
    let viewCount: Int64
    var isAdValue = false

    init(
        name: String, url: String, streamType: StreamType,
        duration: Int64, viewCount: Int64, isAd: Bool = false
    ) {
        self.name = name
        self.url = url
        self.streamType = streamType
        self.duration = duration
        self.viewCount = viewCount
        self.isAdValue = isAd
    }

    func getName() throws -> String { name }
    func getUrl() throws -> String { url }
    func getThumbnails() throws -> [Image] { [] }
    func getStreamType() throws -> StreamType { streamType }
    func isAd() throws -> Bool { isAdValue }
    func getDuration() throws -> Int64 { duration }
    func getViewCount() throws -> Int64 { viewCount }
    func getUploaderName() throws -> String? { "Uploader" }
    func getUploaderUrl() throws -> String? { "https://uploader" }
    func isUploaderVerified() throws -> Bool { false }
    func getTextualUploadDate() throws -> String? { nil }
    func getUploadDate() throws -> DateWrapper? { nil }
}

private struct MockChannelInfoItemExtractor: ChannelInfoItemExtractor {
    let name: String
    let url: String

    func getName() throws -> String { name }
    func getUrl() throws -> String { url }
    func getThumbnails() throws -> [Image] { [] }
    func getDescription() throws -> String? { "desc" }
    func getSubscriberCount() throws -> Int64 { 1000 }
    func getStreamCount() throws -> Int64 { 50 }
    func isVerified() throws -> Bool { true }
}
