// Mirrors: extractor/src/main/java/org/schabi/newpipe/extractor/stream/SubtitlesStream.java @ v0.26.3
//
// Deviation: getDisplayLanguageName falls back to the language tag when the
// platform cannot localize the identifier (Linux Foundation).

import Foundation

public final class SubtitlesStream: Stream {
    private let format: MediaFormat?
    private let locale: Locale
    private let autoGenerated: Bool
    private let code: String

    public final class Builder {
        fileprivate var id: String?
        fileprivate var content: String?
        fileprivate var isUrl = false
        fileprivate var deliveryMethod = DeliveryMethod.PROGRESSIVE_HTTP
        fileprivate var mediaFormat: MediaFormat?
        fileprivate var manifestUrl: String?
        fileprivate var languageCode: String?
        fileprivate var autoGenerated: Bool?

        public init() {}

        @discardableResult
        public func setId(_ id: String) -> Builder {
            self.id = id
            return self
        }

        @discardableResult
        public func setContent(_ content: String, _ isUrl: Bool) -> Builder {
            self.content = content
            self.isUrl = isUrl
            return self
        }

        @discardableResult
        public func setMediaFormat(_ mediaFormat: MediaFormat?) -> Builder {
            self.mediaFormat = mediaFormat
            return self
        }

        @discardableResult
        public func setDeliveryMethod(_ deliveryMethod: DeliveryMethod) -> Builder {
            self.deliveryMethod = deliveryMethod
            return self
        }

        @discardableResult
        public func setManifestUrl(_ manifestUrl: String?) -> Builder {
            self.manifestUrl = manifestUrl
            return self
        }

        @discardableResult
        public func setLanguageCode(_ languageCode: String) -> Builder {
            self.languageCode = languageCode
            return self
        }

        @discardableResult
        public func setAutoGenerated(_ autoGenerated: Bool) -> Builder {
            self.autoGenerated = autoGenerated
            return self
        }

        public func build() throws -> SubtitlesStream {
            precondition(content != nil,
                "No valid content was specified. Please specify a "
                + "valid one with setContent.")
            precondition(languageCode != nil,
                "The language code of the subtitles stream has "
                + "been not set or is null. Make sure you specified an non null language "
                + "code with setLanguageCode.")
            precondition(autoGenerated != nil,
                "The subtitles stream has been not set as an "
                + "autogenerated subtitles stream or not. Please specify this information "
                + "with setIsAutoGenerated.")
            if id == nil {
                id = languageCode! + (mediaFormat != nil ? "." + mediaFormat!.suffix : "")
            }
            return try SubtitlesStream(
                id!, content!, isUrl, mediaFormat, deliveryMethod,
                languageCode!, autoGenerated!, manifestUrl)
        }
    }

    private init(
        _ id: String,
        _ content: String,
        _ isUrl: Bool,
        _ mediaFormat: MediaFormat?,
        _ deliveryMethod: DeliveryMethod,
        _ languageCode: String,
        _ autoGenerated: Bool,
        _ manifestUrl: String?
    ) throws {
        guard let locale = LocaleCompat.forLanguageTag(languageCode) else {
            throw ParsingException("not a valid locale language code: \(languageCode)")
        }
        self.locale = locale
        self.code = languageCode
        self.format = mediaFormat
        self.autoGenerated = autoGenerated
        super.init(id, content, isUrl, mediaFormat, deliveryMethod, manifestUrl)
    }

    public func getExtension() -> String {
        format!.suffix
    }

    public func isAutoGenerated() -> Bool {
        autoGenerated
    }

    public override func equalStats(_ cmp: Stream?) -> Bool {
        guard super.equalStats(cmp), let cmp = cmp as? SubtitlesStream else { return false }
        return code == cmp.code && autoGenerated == cmp.autoGenerated
    }

    public func getDisplayLanguageName() -> String {
        locale.localizedString(forIdentifier: locale.identifier) ?? code
    }

    public func getLanguageTag() -> String {
        code
    }

    public func getLocale() -> Locale {
        locale
    }

    public override func getItagItem() -> ItagItem? {
        nil
    }
}
